easy_admin:
    site_name: 'Genesis | Administration'
    design:
        assets:
            favicon: '/assets/favicon.png'
    entities:
        Post:
            class: App\Entity\Post
            list:
                sort: 'publicationDate'
            search:
                sort: 'publicationDate'
            form:
                fields:
                    - 'title'
                    - { property: 'content', type: 'textarea' }
        Event:
            class: App\Entity\Event
            list:
                sort: ['date', 'ASC']
            search:
                sort: ['date', 'ASC']
            form:
                fields:
                    - 'title'
                    - { property: 'content', type: 'textarea' }
                    - 'location'
                    - { property: 'date', type_options: { widget: 'single_text', format: 'MM-dd-MM-yyyy' } }
                    - { property: 'startsAt', type_options: { widget: 'choice' } }
                    - { property: 'endsAt', type_options: { widget: 'choice' } }


