security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: argon2i
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password:  $argon2i$v=19$m=1024,t=2,p=2$WENoQ05TZ2o1ZWhCWlpGeA$ia1AeLcpPIyU20TFdfO6/P001qKj8+e7ydBBikaDPng
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: easyadmin
            logout: true
            anonymous: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
