vich_uploader:
    db_driver: orm

    mappings:
        post_medias:
            uri_prefix: '%app.path.post_medias%'
            upload_destination: '%kernel.project_dir%/public/assets/posts'
        event_medias:
            uri_prefix: '%app.path.event_medias%'
            upload_destination: '%kernel.project_dir%/public/assets/events'
