easy_admin:
    entities:
        Notification:
            class: App\Entity\Notification
            disabled_actions: ['edit', 'delete']
            list:
                fields:
                    - { property: 'sendAt', label: "Date d'envoie", type: 'date' }
                    - { property: 'title', label: 'Titre' }
                    - 'body'
                    - { property: 'random', label: 'Notification aléatoire', type: 'boolean'}
                    - { property: 'success', label: 'Envoie réusie', type: 'boolean'}
            form:
                fields:
                    - { property: 'title', label: 'Titre', type: 'text'}
                    - { property: 'body', type: 'text'}
                    - { property: 'subtitle', label: 'Substitle (IOS Only)' ,type: 'text'}
                    - { property: 'priority', label: 'Priorité', type: 'choice', type_options: { choices: {default: 'default',normal: 'normal',high: 'high'} } }
                    - { property: 'random', label: 'Aléatoire (Envoyer une seule notification de manière aléatoire)', type: 'checkbox'}