easy_admin:
    entities:
        Post:
            class: App\Entity\Post
            menu:
                label: 'Posts'
                icon: 'newspaper-o'
            list:
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'content', label: 'Contenu' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'publicationDate', label: 'Date de publication', type: 'date' }
                sort: 'publicationDate'
            search:
                sort: 'publicationDate'
            form:
                fields:
                    - { property: 'title', label: 'Titre', type: 'text'}
                    - { property: 'content', label: 'Contenu',type: 'textarea' }
                    - { property: 'link', label: 'Lien', type: 'text' }
                    - { property: 'uploadedFiles', label: 'Images', type: 'file', type_options: { multiple: 'true' } }